[package]
name = "lambubu_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
lambubu = { path = "../lambubu" }
lambubu_church = { path = "../lambubu_church" }

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "reduction"
harness = false
